### ISSUE TITLE
get_fields returns an empty list on Ubuntu 18.04

### ISSUE THREAD

**Issue by wmay** [pridiltal/staplr#40] opened 2019-06-17 22:35 UTC
`get_fields` seems to always return an empty list on Ubuntu 18.04.

```
> library(staplr)
> pdfFile = system.file('testForm.pdf',package = 'staplr')
> fields = get_fields(pdfFile)
Warning message:
In get_fields(pdfFile) :
  some fields seems to include plain text UTF-8. Setting convert_field_names = TRUE might help. These fields have problematic names: 
 weird #C3#91 characters, #E2#80#93weird#E2#80#93 dash, #E2#80#94weird#E2#80#94 long dash, #C2#BD #C2#BE #E2#86#92 #E2#80#98 #E2#80#99 #E2#80#9D #E2#80#9C #E2#80#A2 characters #E2#86#92nospace
> fields
named list()
```

I tried this with both the CRAN and github versions of staplr. I'm using pdftk from the 18.10 repository, as suggested at the [askubuntu link](https://askubuntu.com/a/1028983) in staplr's readme.

I finally tracked this down to the `fdfAnnotate` function. It assumes that values come before names in the FDF file. But in my FDF file the names come first, then values:

```
%FDF-1.2
%\E2\E3\CF\D3
1 0 obj 
<<
/FDF 
<<
/Fields [
<<
/T (#E2#80#94weird#E2#80#94 long dash)
/V ()
>> 
<<
/T (#C2#BD #C2#BE #E2#86#92 #E2#80#98 #E2#80#99 #E2#80#9D #E2#80#9C #E2#80#A2 characters #E2#86#92nospace)
/V ()
>> 
<<
/T (RadioGroup)
/V /Off
>> 
<<
/T (TextField2)
/V ()
>> 
<<
/T (TextField1)
/V ()
>> 
<<
/T (#E2#80#93weird#E2#80#93 dash)
/V ()
>> 
<<
/T (&weird& and)
/V ()
>> 
<<
/T (weird #C3#91 characters)
/V ()
>> 
<<
/T ({weird} things)
/V ()
>> 
<<
/T (\(weird\) paranthesis)
/V ()
>> 
<<
/T (InterstingChar2)
/V (\FE\FF\00\BD\00 \00\BE\00 !\92\00  \00  \00  \00  \00  ")
>> 
<<
/T (TextFieldPage2)
/V ()
>> 
<<
/T (InterstingChar1)
/V (\D1, \F1, \C9, \CD, \D3)
>> 
<<
/T (TextFieldPage3)
/V ()
>> 
<<
/T (hierarchy2)
/Kids [
<<
/T (child2)
/Kids [
<<
/T (node2)
/V ()
>> 
<<
/T (node1)
/V ()
>>]
>> 
<<
/T (child)
/Kids [
<<
/T (node2)
/V ()
>> 
<<
/T (node3)
/V ()
>> 
<<
/T (node1)
/V ()
>>]
>>]
>> 
<<
/T (hierarchy)
/Kids [
<<
/T (node4)
/V ()
>> 
<<
/T (node2)
/V ()
>> 
<<
/T (node3)
/V ()
>> 
<<
/T (node1)
/V ()
>>]
>> 
<<
/T ([weird] brackets)
/V ()
>> 
<<
/T (node1)
/V ()
>> 
<<
/T (InterstingChar3)
/V (\FE\FF\00t\00h\00e\00r\00e\00 \00b\00e\00 \00e\00m\00o\00j\00i\00:\00 \D8=\DC\00 \00a\00n\00d\00 \00s\00o\00m\00e\00 \00w\00i\00s\00e\00 \00m\00o\00n\00k\00e\00y\00 \D8=\DEH\D8=\DEI\D8=\DEJ)
>> 
<<
/T (betweenHierarch)
/V ()
>> 
<<
/T (TextFieldForMoreWeirdChars)
/V ()
>> 
<<
/T ("weird" quotes)
/V ()
>> 
<<
/T (checkBox)
/V /Off
>> 
<<
/T (<weird> tags)
/V ()
>> 
<<
/T (List Box)
/V ()
>>]
>>
>>
endobj 
trailer

<<
/Root 1 0 R
>>
%%EOF
```

**Comment by oganm** [comment] 2019-06-18 02:38
and I thought it was done... thanks for the diagnosis. indeed the file specification ([page 461](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf)) doesn't state a correct order so I shouldn't rely on a stable relationship between `/V` `/T` and `/Kids`. Just pushed a quick and dirty fix for this but will probably rewrite the fdfAnnotate to be more versatile eventually.

**Comment by oganm** [comment] 2019-06-18 02:45
whops. pushed to the wrong branch. should work fine now

**Comment by oganm** [comment] 2019-06-18 03:00
As a side note pdftk-java might be shippable with the package which would be a good quality of life improvement

**Comment by oganm** [comment] 2019-06-18 03:08
Another side note: the difference is likely caused by different implementation in `pdftk-java`. It appears that it is designed to be compatible but there might be other differences between the two and unlike base pdftk, this one is still getting updates. We should probably run the tests on a pdftk-java installation as well to see what else is different.

**Comment by wmay** [comment] 2019-06-18 19:29
I won't comment on what you should do with pdftk-java, but I can confirm that the new version works for me. Nice work!

**Comment by oganm** [comment] 2019-06-18 22:35
Worry not. Those were me mumbling to myself before deciding to open a separate issue. Happy that it works.

**Closed as completed by oganm** 2019-06-18 22:35 UTC
